#!/bin/bash
#PBS -N 1br5_flip_ligH_hoptdefH-3_relaxed-NEWAPI
#PBS -l nodes=1:ppn=4
#PBS -l mem=4GB
#PBS -j oe
#PBS -r n
#PBS -q N5
#PBS -l walltime=1:00:00
cd $PBS_O_WORKDIR

Node=`cat $PBS_NODEFILE | uniq`
NNo=`cat $PBS_NODEFILE | uniq | sed -e 's/node//'`

#if [[ $NNo -gt 12  &&  $NNo -lt 30 ]]
#then
#   TEMP="tmp1"
#else
#   TEMP="tmp"
#fi
TEMP="tmp"


ssh $Node "mkdir -p /$TEMP/$PBS_JOBID"

echo "This job is running on host $Node" > "1br5_flip_ligH_hoptdefH-3_relaxed-NEWAPI.log"
echo "Current directory: $PBS_O_WORKDIR" >> "1br5_flip_ligH_hoptdefH-3_relaxed-NEWAPI.log"
date >> "1br5_flip_ligH_hoptdefH-3_relaxed-NEWAPI.log"
source /share/apps/gaussian/g16-env.sh
source ~/bin/env/aiqm1-env.sh
export GAUSS_SCRDIR=/$TEMP/$PBS_JOBID
echo $GAUSS_SCRDIR >> "1br5_flip_ligH_hoptdefH-3_relaxed-NEWAPI.log"

g16 <1br5_flip_ligH_hoptdefH-3_relaxed-NEWAPI.gjf>> "1br5_flip_ligH_hoptdefH-3_relaxed-NEWAPI.log"

date >> "1br5_flip_ligH_hoptdefH-3_relaxed-NEWAPI.log"

#formchk 1br5_flip_ligH_hoptdefH-3_relaxed-NEWAPI.chk 1br5_flip_ligH_hoptdefH-3_relaxed-NEWAPI.fchk

ssh $Node "rm -rf $GAUSS_SCRDIR"

